### PR TITLE
Get complete data from prismic pagination

### LINKED ISSUE #19: Only one page of paginated data gets used
Prismic has a maximum `pageSize` of 100 and metalsmith-prismic does not pull data from multiple pages. Thus data is incomplete when trying to pull everything from a paginated resource.

### PR DESCRIPTION
**Pull request by nblumoe**
With these changes, metalsmith-prismic pulls data from all pages when a resource is paginated.

fixes #19

### CODE REVIEW

**Comment by nblumoe** [comment]
Tests seem to fail because test data because the API isn't mocked and the response changed.
However, this fix also has one issue: If someone using the lib relies on `pageSize` limiting the number of retrieved documents, this breaks now.
Will send an updated PR when tests were adjusted and a flag parameter introduced to pull all pages (defaulting to the previous behaviour).

**Comment by nblumoe** [comment]
@mbanting thoughts?

**Comment by mbanting** [comment]
This is great @nblumoe, thanks for doing this.

**Comment by nblumoe** [comment]
Thank YOU for building the plugin!

One note: I would say it would be the better default, to always pull all pages. However, I did not want to implement a breaking change and this would change the behavior when people update the plugin. You might want to consider adding a deprecation warning and then in a later release change to an `allPages: true` default.

**Pull request merged**
